# Generated by Django 5.2.3 on 2025-06-26 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='poubelles/', verbose_name='Image')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('annotation', models.CharField(choices=[('pleine', 'Pleine'), ('vide', 'Vide'), ('non_annotee', 'Non annotée')], default='non_annotee', max_length=20, verbose_name='État de la poubelle')),
                ('annotation_automatique', models.CharField(choices=[('pleine', 'Pleine'), ('vide', 'Vide'), ('non_annotee', 'Non annotée')], default='non_annotee', max_length=20, verbose_name='Classification automatique')),
                ('taille_fichier', models.FloatField(blank=True, null=True, verbose_name='Taille (Ko)')),
                ('largeur', models.IntegerField(blank=True, null=True, verbose_name='Largeur (px)')),
                ('hauteur', models.IntegerField(blank=True, null=True, verbose_name='Hauteur (px)')),
                ('couleur_moyenne_r', models.IntegerField(blank=True, null=True, verbose_name='Rouge moyen')),
                ('couleur_moyenne_g', models.IntegerField(blank=True, null=True, verbose_name='Vert moyen')),
                ('couleur_moyenne_b', models.IntegerField(blank=True, null=True, verbose_name='Bleu moyen')),
                ('luminance_moyenne', models.FloatField(blank=True, null=True, verbose_name='Luminance moyenne')),
                ('contraste', models.FloatField(blank=True, null=True, verbose_name='Niveau de contraste')),
                ('localisation', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Annotation d'image",
                'verbose_name_plural': "Annotations d'images",
                'ordering': ['-date_ajout'],
            },
        ),
    ]
